In the second week, we have to go with a input system and face an online on naive bayes classifier.
In the first line there are three numbers : Number of features, Number of classes and Number of samples.

In [1]:
import numpy as np
import math

Function for loading data from file

In [2]:

features=0
classes=0
samples=0

def data_loader(filename,isTrainData):
    # open data file
    file = open("during evaluation/"+filename,"r")


    # initialize
    i=0
    global features
    global classes
    global samples


    listx = []
    listy = []

    for line in file:
        # for the first line
        if(i==0 and isTrainData==1):
            fields = line.split()

            features = int(fields[0])
            classes = int(fields[1])
            samples = int(fields[2])
        # for the rest of the line
        else:
            fields = line.split()
            templist = []

            for j in range(features):
                #print(fields[j])
                templist.append(float(fields[j]))

            listx.append(templist)
            listy.append(int(fields[features]))

        i = i+1

    #print(str(features)+" "+str(classes)+" "+str(samples))

    # convert into numpy array
    x = np.array(listx)
    y = np.array(listy)

    #print(x.shape, y.shape)
    
    return x,y


Load train data

In [3]:
train_x,train_y =  data_loader("Train.txt",1)
print(train_x.shape,train_y.shape)

(100, 2) (100,)


Load test data

In [4]:
test_x,test_y =  data_loader("Test.txt",0)
print(test_x.shape,test_y.shape)

(100, 2) (100,)


In [5]:
print("Features: "+str(features)+"\nClasses: "+str(classes)+"\nSamples: "+str(samples))

Features: 2
Classes: 2
Samples: 100


Calculating prior probability

In [6]:
pre_prob = np.zeros((1, classes))

for i in range(classes):
    total = (train_y==(i+1)).sum()
    pre_prob[0][i] = total/(samples)
print(pre_prob)

[[0.5 0.5]]


calculate mean and deviation

In [7]:
mean = np.zeros((features,classes))
deviation = np.zeros((features,classes))

for i in range(features):
    for j in range(classes):
        value = 0.0
        for k in range(samples):
            if(train_y[k]==(j+1)):
                value =  value + train_x[k][i]
        mean[i][j]=value/(train_y==(j+1)).sum()
print(mean)
for i in range(features):
    for j in range(classes):
        value = 0.0
        for k in range(samples):
            if(train_y[k]==(j+1)):
                value = value+ (train_x[k][i] - mean[i][j])*(train_x[k][i] - mean[i][j])
        deviation[i][j]=value/(train_y==(j+1)).sum()
print(deviation)            

[[ 2.01143   7.803882]
 [ 4.057054 10.073138]]
[[0.25451926 0.17793744]
 [0.25819941 0.19076063]]


Caluculate gaussian distribution

In [8]:
def gauss(value,class_no,feature_no):
    global mean
    global deviation
    expo = -(value-mean[feature_no][class_no])*(value-mean[feature_no][class_no])
    expo = expo/(2*deviation[feature_no][class_no])
    expo = math.exp(expo)
    co_eff = 1/math.sqrt(2.0*3.1416*deviation[feature_no][class_no])
    
    return co_eff*expo

Calculating for test data

In [9]:
predict = np.zeros((samples,1))
for i in range(samples):
    
    prob_list = []
    for j in range(classes):
        value = 1.0
        for k in range(features):
            value = value * gauss(test_x[i][k],j,k)
        prob_list.append(value*pre_prob[0][j])
    pos = prob_list.index(max(prob_list))
    predict[i] = pos+1
print(predict)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


Calculate accuracy

In [10]:
correct = 0
for i in range(samples):
    if test_y[i] == int(predict[i][0]):
        correct = correct+1
    else:
        feature_str=""
        for j in range(features):
            feature_str = feature_str +str(test_x[i][j])
        print(str(i+1)+" "+feature_str +" "+str(test_y[i])+" "+str(int(predict[i][0])))
print("Accuracy : " +str((correct*100)/samples))

49 8.462910.0512 1 2
50 8.875710.9795 1 2
51 1.87621.4066 2 1
52 1.74461.7209 2 1
Accuracy : 96.0
